# Generated by Django 5.1.3 on 2024-11-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
